import { Movie } from "@/types/movieType";

export const movies: Movie[] = [
  {
    id: "121",
    name: "Your Name.",
    year: "2016",
    runTime: "106",
    rating: "8.4",
    votes: "300107",
    metaScore: "81",
    gross: "5020000",
    genre: ["Animation", "Drama", "Fantasy"],
    certification: "PG",
    director: ["Makoto Shinkai"],
    stars: [
      "Ryunosuke Kamiki",
      "Mone Kamishiraishi",
      "Ryo Narita",
      "Aoi YÃ»ki",
    ],
    description: [
      "Two",
      "teenagers",
      "share",
      "a",
      "profound,",
      "magical",
      "connection",
      "upon",
      "discovering",
      "they",
      "are",
      "swapping",
      "bodies.",
      "Things",
      "manage",
      "to",
      "become",
      "even",
      "more",
      "complicated",
      "when",
      "the",
      "boy",
      "and",
      "girl",
      "decide",
      "to",
      "meet",
      "in",
      "person.",
    ],
  }, // Your Name.
  {
    id: "31",
    name: "Spider-Man: Across the Spider-Verse",
    year: "2023",
    runTime: "140",
    rating: "8.7",
    votes: "270500",
    metaScore: "86",
    gross: "",
    genre: ["Animation", "Action", "Adventure"],
    certification: "PG",
    director: ["Joaquim Dos Santos", "Kemp Powers", "Justin K. Thompson"],
    stars: [
      "Shameik Moore",
      "Hailee Steinfeld",
      "Brian Tyree Henry",
      "Luna Lauren Velez",
    ],
    description: [
      "Miles",
      "Morales",
      "catapults",
      "across",
      "the",
      "Multiverse,",
      "where",
      "he",
      "encounters",
      "a",
      "team",
      "of",
      "Spider-People",
      "charged",
      "with",
      "protecting",
      "its",
      "very",
      "existence.",
      "When",
      "the",
      "heroes",
      "clash",
      "on",
      "how",
      "to",
      "handle",
      "a",
      "new",
      "threat,",
      "Miles",
      "must",
      "redefine",
      "what",
      "it",
      "means",
      "to",
      "be",
      "a",
      "hero.",
    ],
  }, // Across the Spider-Verse
  {
    id: "2437",
    name: "Tenet",
    year: "2020",
    runTime: "150",
    rating: "7.3",
    votes: "562572",
    metaScore: "69",
    gross: "58460000",
    genre: ["Action", "Sci-Fi", "Thriller"],
    certification: "PG-13",
    director: ["Christopher Nolan"],
    stars: [
      "John David Washington",
      "Robert Pattinson",
      "Elizabeth Debicki",
      "Juhan Ulfsak",
    ],
    description: [
      "Armed",
      "with",
      "only",
      "one",
      "word,",
      "Tenet,",
      "and",
      "fighting",
      "for",
      "the",
      "survival",
      "of",
      "the",
      "entire",
      "world,",
      "a",
      "Protagonist",
      "journeys",
      "through",
      "a",
      "twilight",
      "world",
      "of",
      "international",
      "espionage",
      "on",
      "a",
      "mission",
      "that",
      "will",
      "unfold",
      "in",
      "something",
      "beyond",
      "real",
      "time.",
    ],
  }, // Tenet
  {
    id: "863",
    name: "The Batman",
    year: "2022",
    runTime: "176",
    rating: "7.8",
    votes: "734920",
    metaScore: "72",
    gross: "369350000",
    genre: ["Action", "Crime", "Drama"],
    certification: "PG-13",
    director: ["Matt Reeves"],
    stars: [
      "Robert Pattinson",
      "ZoÃ« Kravitz",
      "Jeffrey Wright",
      "Colin Farrell",
    ],
    description: [
      "When",
      "a",
      "sadistic",
      "serial",
      "killer",
      "begins",
      "murdering",
      "key",
      "political",
      "figures",
      "in",
      "Gotham,",
      "Batman",
      "is",
      "forced",
      "to",
      "investigate",
      "the",
      "city's",
      "hidden",
      "corruption",
      "and",
      "question",
      "his",
      "family's",
      "involvement.",
    ],
  }, // The Batman
  {
    id: "1",
    name: "The Godfather",
    year: "1972",
    runTime: "175",
    rating: "9.2",
    votes: "1954174",
    metaScore: "100",
    gross: "134970000",
    genre: ["Crime", "Drama"],
    certification: "R",
    director: ["Francis Ford Coppola"],
    stars: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
    description: [
      "Don",
      "Vito",
      "Corleone,",
      "head",
      "of",
      "a",
      "mafia",
      "family,",
      "decides",
      "to",
      "hand",
      "over",
      "his",
      "empire",
      "to",
      "his",
      "youngest",
      "son",
      "Michael.",
      "However,",
      "his",
      "decision",
      "unintentionally",
      "puts",
      "the",
      "lives",
      "of",
      "his",
      "loved",
      "ones",
      "in",
      "grave",
      "danger.",
    ],
  }, // The God Father
  {
    id: "49",
    name: "Oppenheimer",
    year: "2023",
    runTime: "180",
    rating: "8.6",
    votes: "451781",
    metaScore: "88",
    gross: "",
    genre: ["Biography", "Drama", "History"],
    certification: "R",
    director: ["Christopher Nolan"],
    stars: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    description: [
      "The",
      "story",
      "of",
      "American",
      "scientist,",
      "J.",
      "Robert",
      "Oppenheimer,",
      "and",
      "his",
      "role",
      "in",
      "the",
      "development",
      "of",
      "the",
      "atomic",
      "bomb.",
    ],
  }, // Oppenheimer
  {
    id: "107",
    name: "The Dark Knight Rises",
    year: "2012",
    runTime: "164",
    rating: "8.4",
    votes: "1779181",
    metaScore: "78",
    gross: "448140000",
    genre: ["Action", "Drama", "Thriller"],
    certification: "PG-13",
    director: ["Christopher Nolan"],
    stars: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Gary Oldman"],
    description: [
      "Eight",
      "years",
      "after",
      "the",
      "Joker's",
      "reign",
      "of",
      "chaos,",
      "Batman",
      "is",
      "coerced",
      "out",
      "of",
      "exile",
      "with",
      "the",
      "assistance",
      "of",
      "the",
      "mysterious",
      "Selina",
      "Kyle",
      "in",
      "order",
      "to",
      "defend",
      "Gotham",
      "City",
      "from",
      "the",
      "vicious",
      "guerrilla",
      "terrorist",
      "Bane.",
    ],
  }, // The Dark Knight Rises
  {
    id: "233",
    name: "Shutter Island",
    year: "2010",
    runTime: "138",
    rating: "8.2",
    votes: "1398809",
    metaScore: "63",
    gross: "128010000",
    genre: ["Mystery", "Thriller"],
    certification: "R",
    director: ["Martin Scorsese"],
    stars: [
      "Leonardo DiCaprio",
      "Emily Mortimer",
      "Mark Ruffalo",
      "Ben Kingsley",
    ],
    description: [
      "Teddy",
      "Daniels",
      "and",
      "Chuck",
      "Aule,",
      "two",
      "US",
      "marshals,",
      "are",
      "sent",
      "to",
      "an",
      "asylum",
      "on",
      "a",
      "remote",
      "island",
      "in",
      "order",
      "to",
      "investigate",
      "the",
      "disappearance",
      "of",
      "a",
      "patient,",
      "where",
      "Teddy",
      "uncovers",
      "a",
      "shocking",
      "truth",
      "about",
      "the",
      "place.",
    ],
  }, // Shutter Island
  {
    id: "232",
    name: "Spider-Man: No Way Home",
    year: "2021",
    runTime: "148",
    rating: "8.2",
    votes: "833734",
    metaScore: "71",
    gross: "804750000",
    genre: ["Action", "Adventure", "Fantasy"],
    certification: "PG-13",
    director: ["Jon Watts"],
    stars: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon"],
    description: [
      "With",
      '"Spider-Man\'s"',
      "identity",
      "now",
      "revealed,",
      "Peter",
      "asks",
      "Doctor",
      "Strange",
      "for",
      "help.",
      "When",
      "a",
      "spell",
      "goes",
      "wrong,",
      "dangerous",
      "foes",
      "from",
      "other",
      "worlds",
      "start",
      "to",
      "appear,",
      "forcing",
      "Peter",
      "to",
      "discover",
      "what",
      "it",
      "truly",
      "means",
      "to",
      "be",
      "Spider-Man.",
    ],
  }, // Spider-Man: No Way Home
  {
    id: "178",
    name: "Vikram",
    year: "2022",
    runTime: "175",
    rating: "8.3",
    votes: "67117",
    metaScore: "",
    gross: "",
    genre: ["Action", "Crime", "Thriller"],
    certification: "R",
    director: ["Lokesh Kanagaraj"],
    stars: ["Kamal Haasan", "Vijay Sethupathi", "Fahadh Faasil", "Narain"],
    description: [
      "A",
      "special",
      "investigator",
      "assigned",
      "a",
      "case",
      "of",
      "serial",
      "killings",
      "discovers",
      "the",
      "case",
      "is",
      "not",
      "what",
      "it",
      "seems",
      "to",
      "be,",
      "and",
      "leading",
      "down",
      "this",
      "path",
      "is",
      "only",
      "going",
      "to",
      "end",
      "in",
      "a",
      "war",
      "between",
      "everyone",
      "involved.",
    ],
  }, // Vikram
  {
    id: "237",
    name: "Batman Begins",
    year: "2005",
    runTime: "140",
    rating: "8.2",
    votes: "1537037",
    metaScore: "70",
    gross: "206850000",
    genre: ["Action", "Crime", "Drama"],
    certification: "PG-13",
    director: ["Christopher Nolan"],
    stars: ["Christian Bale", "Michael Caine", "Ken Watanabe", "Liam Neeson"],
    description: [
      "After",
      "witnessing",
      "his",
      "parents'",
      "death,",
      "Bruce",
      "learns",
      "the",
      "art",
      "of",
      "fighting",
      "to",
      "confront",
      "injustice.",
      "When",
      "he",
      "returns",
      "to",
      "Gotham",
      "as",
      "Batman,",
      "he",
      "must",
      "stop",
      "a",
      "secret",
      "society",
      "that",
      "intends",
      "to",
      "destroy",
      "the",
      "city.",
    ],
  }, // Batman Begins
  {
    id: "4",
    name: "The Dark Knight",
    year: "2008",
    runTime: "152",
    rating: "9",
    votes: "2786129",
    metaScore: "84",
    gross: "534860000",
    genre: ["Action", "Crime", "Drama"],
    certification: "PG-13",
    director: ["Christopher Nolan"],
    stars: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    description: [
      "When",
      "the",
      "menace",
      "known",
      "as",
      "the",
      "Joker",
      "wreaks",
      "havoc",
      "and",
      "chaos",
      "on",
      "the",
      "people",
      "of",
      "Gotham,",
      "Batman",
      "must",
      "accept",
      "one",
      "of",
      "the",
      "greatest",
      "psychological",
      "and",
      "physical",
      "tests",
      "of",
      "his",
      "ability",
      "to",
      "fight",
      "injustice.",
    ],
  }, // The Dark Knight
  {
    id: "18",
    name: "Inception",
    year: "2010",
    runTime: "148",
    rating: "8.8",
    votes: "2473068",
    metaScore: "74",
    gross: "292580000",
    genre: ["Action", "Adventure", "Sci-Fi"],
    certification: "PG-13",
    director: ["Christopher Nolan"],
    stars: [
      "Leonardo DiCaprio",
      "Joseph Gordon-Levitt",
      "Elliot Page",
      "Ken Watanabe",
    ],
    description: [
      "A",
      "thief",
      "who",
      "steals",
      "corporate",
      "secrets",
      "through",
      "the",
      "use",
      "of",
      "dream-sharing",
      "technology",
      "is",
      "given",
      "the",
      "inverse",
      "task",
      "of",
      "planting",
      "an",
      "idea",
      "into",
      "the",
      "mind",
      "of",
      "a",
      "C.E.O.,",
      "but",
      "his",
      "tragic",
      "past",
      "may",
      "doom",
      "the",
      "project",
      "and",
      "his",
      "team",
      "to",
      "disaster.",
    ],
  }, // Inception
  {
    id: "32",
    name: "Interstellar",
    year: "2014",
    runTime: "169",
    rating: "8.7",
    votes: "1995139",
    metaScore: "74",
    gross: "188020000",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    certification: "PG-13",
    director: ["Christopher Nolan"],
    stars: [
      "Matthew McConaughey",
      "Anne Hathaway",
      "Jessica Chastain",
      "Mackenzie Foy",
    ],
    description: [
      "When",
      "Earth",
      "becomes",
      "uninhabitable",
      "in",
      "the",
      "future,",
      "a",
      "farmer",
      "and",
      "ex-NASA",
      "pilot,",
      "Joseph",
      "Cooper,",
      "is",
      "tasked",
      "to",
      "pilot",
      "a",
      "spacecraft,",
      "along",
      "with",
      "a",
      "team",
      "of",
      "researchers,",
      "to",
      "find",
      "a",
      "new",
      "planet",
      "for",
      "humans.",
    ],
  }, // Interstellar
  {
    id: "506",
    name: "Donnie Darko",
    year: "2001",
    runTime: "113",
    rating: "8",
    votes: "830937",
    metaScore: "88",
    gross: "1480000",
    genre: ["Drama", "Mystery", "Sci-Fi"],
    certification: "R",
    director: ["Richard Kelly"],
    stars: [
      "Jake Gyllenhaal",
      "Jena Malone",
      "Mary McDonnell",
      "Holmes Osborne",
    ],
    description: [
      "After",
      "narrowly",
      "escaping",
      "a",
      "bizarre",
      "accident,",
      "a",
      "troubled",
      "teenager",
      "is",
      "plagued",
      "by",
      "visions",
      "of",
      "a",
      "man",
      "in",
      "a",
      "large",
      "rabbit",
      "suit",
      "who",
      "manipulates",
      "him",
      "to",
      "commit",
      "a",
      "series",
      "of",
      "crimes.",
    ],
  }, // Donnie Darko
  {
    id: "1380",
    name: "Avatar: The Way of Water",
    year: "2022",
    runTime: "192",
    rating: "7.6",
    votes: "461810",
    metaScore: "67",
    gross: "659680000",
    genre: ["Action", "Adventure", "Fantasy"],
    certification: "PG-13",
    director: ["James Cameron"],
    stars: [
      "Sam Worthington",
      "Zoe Saldana",
      "Sigourney Weaver",
      "Stephen Lang",
    ],
    description: [
      "Jake",
      "Sully",
      "lives",
      "with",
      "his",
      "newfound",
      "family",
      "formed",
      "on",
      "the",
      "extrasolar",
      "moon",
      "Pandora.",
      "Once",
      "a",
      "familiar",
      "threat",
      "returns",
      "to",
      "finish",
      "what",
      "was",
      "previously",
      "started,",
      "Jake",
      "must",
      "work",
      "with",
      "Neytiri",
      "and",
      "the",
      "army",
      "of",
      "the",
      "Na'vi",
      "race",
      "to",
      "protect",
      "their",
      "home.",
    ],
  }, // Avatar: The Way of Water
  {
    id: "7478",
    name: "Justice League",
    year: "2017",
    runTime: "120",
    rating: "6.1",
    votes: "470120",
    metaScore: "45",
    gross: "229020000",
    genre: ["Action", "Adventure", "Fantasy"],
    certification: "PG-13",
    director: ["Zack Snyder"],
    stars: ["Ben Affleck", "Gal Gadot", "Jason Momoa", "Ezra Miller"],
    description: [
      "Fueled",
      "by",
      "his",
      "restored",
      "faith",
      "in",
      "humanity",
      "and",
      "inspired",
      "by",
      "Superman's",
      "selfless",
      "act,",
      "Bruce",
      "Wayne",
      "enlists",
      "the",
      "help",
      "of",
      "his",
      "new-found",
      "ally,",
      "Diana",
      "Prince,",
      "to",
      "face",
      "an",
      "even",
      "greater",
      "enemy.",
    ],
  }, // Justice League
  {
    id: "929",
    name: "Jujutsu Kaisen 0",
    year: "2021",
    runTime: "112",
    rating: "7.8",
    votes: "28987",
    metaScore: "71",
    gross: "34540000",
    genre: ["Animation", "Action", "Fantasy"],
    certification: "PG-13",
    director: ["Seong-Hu Park"],
    stars: ["Chinatsu Akasaki", "Aya EndÃ`", "Kana Hanazawa", "Show Hayami"],
    description: [
      "Yuta",
      "Okkotsu,",
      "a",
      "high",
      "schooler",
      "who",
      "gains",
      "control",
      "of",
      "an",
      "extremely",
      "powerful",
      "Cursed",
      "Spirit",
      "and",
      "gets",
      "enrolled",
      "in",
      "the",
      "Tokyo",
      "Prefectural",
      "Jujutsu",
      "High",
      "School",
      "by",
      "Jujutsu",
      "Sorcerers",
      "to",
      "help",
      "him",
      "control",
      "his",
      "power",
      "and",
      "keep",
      "an",
      "eye",
      "on",
      "him.",
    ],
  }, // Jujustsu Kaisen 0
  {
    id: "926",
    name: "Captain Phillips",
    year: "2013",
    runTime: "134",
    rating: "7.8",
    votes: "481564",
    metaScore: "82",
    gross: "107100000",
    genre: ["Action", "Biography", "Crime"],
    certification: "PG-13",
    director: ["Paul Greengrass"],
    stars: [
      "Tom Hanks",
      "Barkhad Abdi",
      "Barkhad Abdirahman",
      "Catherine Keener",
    ],
    description: [
      "The",
      "true",
      "story",
      "of",
      "Captain",
      "Richard",
      "Phillips",
      "and",
      "the",
      "2009",
      "hijacking",
      "by",
      "Somali",
      "pirates",
      "of",
      "the",
      "U.S.-flagged",
      "MV",
      "Maersk",
      "Alabama,",
      "the",
      "first",
      "American",
      "cargo",
      "ship",
      "to",
      "be",
      "hijacked",
      "in",
      "two",
      "hundred",
      "years.",
    ],
  }, // Captain Phillips

  {
    id: "113",
    name: "Raiders of the Lost Ark",
    year: "1981",
    runTime: "115",
    rating: "8.4",
    votes: "1014569",
    metaScore: "86",
    gross: "248160000",
    genre: ["Action", "Adventure"],
    certification: "PG",
    director: ["Steven Spielberg"],
    stars: ["Harrison Ford", "Karen Allen", "Paul Freeman", "John Rhys-Davies"],
    description: [
      "In",
      "1936,",
      "archaeologist",
      "and",
      "adventurer",
      "Indiana",
      "Jones",
      "is",
      "hired",
      "by",
      "the",
      "U.S.",
      "government",
      "to",
      "find",
      "the",
      "Ark",
      "of",
      "the",
      "Covenant",
      "before",
      "the",
      "Nazis",
      "can",
      "obtain",
      "its",
      "awesome",
      "powers.",
    ],
  },
  {
    id: "111",
    name: "Amadeus",
    year: "1984",
    runTime: "160",
    rating: "8.4",
    votes: "417725",
    metaScore: "87",
    gross: "51970000",
    genre: ["Biography", "Drama", "Music"],
    certification: "R",
    director: ["Milos Forman"],
    stars: [
      "F. Murray Abraham",
      "Tom Hulce",
      "Elizabeth Berridge",
      "Roy Dotrice",
    ],
    description: [
      "The",
      "life,",
      "success",
      "and",
      "troubles",
      "of",
      "Wolfgang",
      "Amadeus",
      "Mozart,",
      "as",
      "told",
      "by",
      "Antonio",
      "Salieri,",
      "the",
      "contemporaneous",
      "composer",
      "who",
      "was",
      "deeply",
      "jealous",
      "of",
      "Mozart's",
      "talent",
      "and",
      "claimed",
      "to",
      "have",
      "murdered",
      "him.",
    ],
  },
  {
    id: "518",
    name: "The King's Speech",
    year: "2010",
    runTime: "118",
    rating: "8",
    votes: "697979",
    metaScore: "88",
    gross: "138800000",
    genre: ["Biography", "Drama", "History"],
    certification: "R",
    director: ["Tom Hooper"],
    stars: [
      "Colin Firth",
      "Geoffrey Rush",
      "Helena Bonham Carter",
      "Derek Jacobi",
    ],
    description: [
      "The",
      "story",
      "of",
      "King",
      "George",
      "VI,",
      "his",
      "unexpected",
      "ascension",
      "to",
      "the",
      "throne",
      "of",
      "the",
      "British",
      "Empire",
      "in",
      "1936,",
      "and",
      "the",
      "speech",
      "therapist",
      "who",
      "helped",
      "the",
      "unsure",
      "monarch",
      "overcome",
      "his",
      "stammer.",
    ],
  },
  {
    id: "1220",
    name: "The Last Emperor",
    year: "1987",
    runTime: "163",
    rating: "7.7",
    votes: "108719",
    metaScore: "76",
    gross: "43980000",
    genre: ["Biography", "Drama", "History"],
    certification: "PG-13",
    director: ["Bernardo Bertolucci"],
    stars: ["John Lone", "Joan Chen", "Peter O'Toole", "Ruocheng Ying"],
    description: [
      "Bernardo",
      "Bertolucci's",
      "Oscar-winning",
      "dramatisation",
      "of",
      "the",
      "life",
      "story",
      "of",
      "China's",
      "last",
      "emperor,",
      "Pu",
      "Yi.",
    ],
  },
  {
    id: "3",
    name: "The Chaos Class",
    year: "1975",
    runTime: "87",
    rating: "9.2",
    votes: "42231",
    metaScore: "",
    gross: "",
    genre: ["Comedy", "Drama"],
    certification: "PG",
    director: ["Ertem Egilmez"],
    stars: ["Kemal Sunal", "MÃ¼nir Ã-zkul", "Halit AkÃ§atepe", "Tarik Akan"],
    description: [
      "Lazy,",
      "uneducated",
      "students",
      "share",
      "a",
      "very",
      "close",
      "bond.",
      "They",
      "live",
      "together",
      "in",
      "the",
      "dormitory,",
      "where",
      "they",
      "plan",
      "their",
      "latest",
      "pranks.",
      "When",
      "a",
      "new",
      "headmaster",
      "arrives,",
      "the",
      "students",
      "naturally",
      "try",
      "to",
      "overthrow",
      "him.",
      "A",
      "comic",
      "war",
      "of",
      "nitwits",
      "follows.",
    ],
  },
  {
    id: "14",
    name: "Tosun Pasa",
    year: "1976",
    runTime: "90",
    rating: "8.9",
    votes: "24170",
    metaScore: "",
    gross: "",
    genre: ["Comedy"],
    certification: "PG",
    director: ["Kartal Tibet"],
    stars: ["Kemal Sunal", "MÃ¼jde Ar", "Adile Nasit", "Sener Sen"],
    description: [
      "Two",
      "traditionally",
      "rival",
      "Turkish",
      "families,",
      "'Seferoglu's",
      "and",
      "'Tellioglu's",
      "are",
      "competing",
      "for",
      "the",
      "'Green",
      "Valley'.",
      "The",
      "winner",
      "will",
      "be",
      "determined",
      "by",
      "Daver",
      "Bey,",
      "who",
      "has",
      "a",
      "beautiful",
      "young",
      "daughter,...",
      "See",
      "full",
      "summary",
      "Â»",
    ],
  },
  {
    id: "98",
    name: "Jersey",
    year: "2019",
    runTime: "157",
    rating: "8.5",
    votes: "20723",
    metaScore: "",
    gross: "",
    genre: ["Drama", "Sport"],
    certification: "Not Rated",
    director: ["Gowtam Tinnanuri"],
    stars: ["Nani", "Shraddha Srinath", "Sathyaraj", "Ronit Kamra"],
    description: [
      "A",
      "failed",
      "cricketer",
      "decides",
      "to",
      "revive",
      "his",
      "cricketing",
      "career",
      "in",
      "his",
      "late",
      "30's",
      "despite",
      "everyone",
      "being",
      "skeptical",
      "of",
      "his",
      "ability",
      "to",
      "do",
      "so.",
    ],
  },
  {
    id: "120",
    name: "3 Idiots",
    year: "2009",
    runTime: "170",
    rating: "8.4",
    votes: "419105",
    metaScore: "67",
    gross: "6530000",
    genre: ["Comedy", "Drama"],
    certification: "PG-13",
    director: ["Rajkumar Hirani"],
    stars: ["Aamir Khan", "Madhavan", "Mona Singh", "Sharman Joshi"],
    description: [
      "Two",
      "friends",
      "are",
      "searching",
      "for",
      "their",
      "long",
      "lost",
      "companion.",
      "They",
      "revisit",
      "their",
      "college",
      "days",
      "and",
      "recall",
      "the",
      "memories",
      "of",
      "their",
      "friend",
      "who",
      "inspired",
      "them",
      "to",
      "think",
      "differently,",
      "even",
      "as",
      "the",
      "rest",
      "of",
      "the",
      "world",
      "called",
      "them",
      "'idiots'.",
    ],
  },
  {
    id: "130",
    name: "The Great Dictator",
    year: "1940",
    runTime: "125",
    rating: "8.4",
    votes: "232323",
    metaScore: "",
    gross: "290000",
    genre: ["Comedy", "Drama", "War"],
    certification: "G",
    director: ["Charles Chaplin"],
    stars: [
      "Charles Chaplin",
      "Paulette Goddard",
      "Jack Oakie",
      "Reginald Gardiner",
    ],
    description: [
      "Dictator",
      "Adenoid",
      "Hynkel",
      "tries",
      "to",
      "expand",
      "his",
      "empire",
      "while",
      "a",
      "poor",
      "Jewish",
      "barber",
      "tries",
      "to",
      "avoid",
      "persecution",
      "from",
      "Hynkel's",
      "regime.",
    ],
  },
  {
    id: "279",
    name: "Children of Heaven",
    year: "1997",
    runTime: "89",
    rating: "8.2",
    votes: "78367",
    metaScore: "77",
    gross: "930000",
    genre: ["Drama", "Family", "Sport"],
    certification: "PG",
    director: ["Majid Majidi"],
    stars: [
      "Mohammad Amir Naji",
      "Amir Farrokh Hashemian",
      "Bahare Seddiqi",
      "Nafise Jafar-Mohammadi",
    ],
    description: [
      "After",
      "a",
      "boy",
      "loses",
      "his",
      "sister's",
      "pair",
      "of",
      "shoes,",
      "he",
      "goes",
      "on",
      "a",
      "series",
      "of",
      "adventures",
      "in",
      "order",
      "to",
      "find",
      "them.",
      "When",
      "he",
      "can't,",
      "he",
      "tries",
      "a",
      "new",
      "way",
      "to",
      "'win'",
      "a",
      "new",
      "pair.",
    ],
  },
  {
    id: "311",
    name: "Bhaag Milkha Bhaag",
    year: "2013",
    runTime: "186",
    rating: "8.2",
    votes: "70761",
    metaScore: "",
    gross: "1630000",
    genre: ["Biography", "Drama", "Sport"],
    certification: "Not Rated",
    director: ["Rakeysh Omprakash Mehra"],
    stars: [
      "Farhan Akhtar",
      "Deepak Singh Rawat",
      "Japtej Singh",
      "Divya Dutta",
    ],
    description: [
      "The",
      "truth",
      "behind",
      "the",
      "ascension",
      "of",
      "Milkha",
      "Singh,",
      "who",
      "was",
      "scarred",
      "by",
      "of",
      "the",
      "India-Pakistan",
      "partition.",
    ],
  },
  {
    id: "353",
    name: "Rocky",
    year: "1976",
    runTime: "120",
    rating: "8.1",
    votes: "610802",
    metaScore: "70",
    gross: "117240000",
    genre: ["Drama", "Sport"],
    certification: "PG",
    director: ["John G. Avildsen"],
    stars: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Carl Weathers"],
    description: [
      "A",
      "small-time",
      "Philadelphia",
      "boxer",
      "gets",
      "a",
      "supremely",
      "rare",
      "chance",
      "to",
      "fight",
      "the",
      "world",
      "heavyweight",
      "champion",
      "in",
      "a",
      "bout",
      "in",
      "which",
      "he",
      "strives",
      "to",
      "go",
      "the",
      "distance",
      "for",
      "his",
      "self-respect.",
    ],
  },
  {
    id: "362",
    name: "Warrior",
    year: "2011",
    runTime: "140",
    rating: "8.1",
    votes: "488106",
    metaScore: "71",
    gross: "13660000",
    genre: ["Action", "Drama", "Sport"],
    certification: "PG-13",
    director: ["Gavin O'Connor"],
    stars: ["Tom Hardy", "Nick Nolte", "Joel Edgerton", "Jennifer Morrison"],
    description: [
      "The",
      "youngest",
      "son",
      "of",
      "an",
      "alcoholic",
      "former",
      "boxer",
      "returns",
      "home,",
      "where",
      "he's",
      "trained",
      "by",
      "his",
      "father",
      "for",
      "competition",
      "in",
      "a",
      "mixed",
      "martial",
      "arts",
      "tournament",
      "-",
      "a",
      "path",
      "that",
      "puts",
      "the",
      "fighter",
      "on",
      "a",
      "collision",
      "course",
      "with",
      "his",
      "estranged,",
      "older",
      "brother.",
    ],
  },
  {
    id: "19",
    name: "Forrest Gump",
    year: "1994",
    runTime: "142",
    rating: "8.8",
    votes: "2182826",
    metaScore: "82",
    gross: "330250000",
    genre: ["Drama", "Romance"],
    certification: "PG-13",
    director: ["Robert Zemeckis"],
    stars: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    description: [
      "The",
      "history",
      "of",
      "the",
      "United",
      "States",
      "from",
      "the",
      "1950s",
      "to",
      "the",
      "70s",
      "unfolds",
      "from",
      "the",
      "perspective",
      "of",
      "an",
      "Alabama",
      "man",
      "with",
      "an",
      "IQ",
      "of",
      "75,",
      "who",
      "yearns",
      "to",
      "be",
      "reunited",
      "with",
      "his",
      "childhood",
      "sweetheart.",
    ],
  },
  {
    id: "58",
    name: "Life Is Beautiful",
    year: "1997",
    runTime: "116",
    rating: "8.6",
    votes: "723773",
    metaScore: "59",
    gross: "57600000",
    genre: ["Comedy", "Drama", "Romance"],
    certification: "PG-13",
    director: ["Roberto Benigni"],
    stars: [
      "Roberto Benigni",
      "Nicoletta Braschi",
      "Giorgio Cantarini",
      "Giustino Durano",
    ],
    description: [
      "When",
      "an",
      "open-minded",
      "Jewish",
      "waiter",
      "and",
      "his",
      "son",
      "become",
      "victims",
      "of",
      "the",
      "Holocaust,",
      "he",
      "uses",
      "a",
      "perfect",
      "mixture",
      "of",
      "will,",
      "humor",
      "and",
      "imagination",
      "to",
      "protect",
      "his",
      "son",
      "from",
      "the",
      "dangers",
      "around",
      "their",
      "camp.",
    ],
  },
  {
    id: "83",
    name: "Casablanca",
    year: "1942",
    runTime: "102",
    rating: "8.5",
    votes: "592666",
    metaScore: "100",
    gross: "1020000",
    genre: ["Drama", "Romance", "War"],
    certification: "PG",
    director: ["Michael Curtiz"],
    stars: [
      "Humphrey Bogart",
      "Ingrid Bergman",
      "Paul Henreid",
      "Claude Rains",
    ],
    description: [
      "A",
      "cynical",
      "expatriate",
      "American",
      "cafe",
      "owner",
      "struggles",
      "to",
      "decide",
      "whether",
      "or",
      "not",
      "to",
      "help",
      "his",
      "former",
      "lover",
      "and",
      "her",
      "fugitive",
      "husband",
      "escape",
      "the",
      "Nazis",
      "in",
      "French",
      "Morocco.",
    ],
  },
  {
    id: "84",
    name: "Cinema Paradiso",
    year: "1988",
    runTime: "155",
    rating: "8.5",
    votes: "274382",
    metaScore: "80",
    gross: "11990000",
    genre: ["Drama", "Romance"],
    certification: "R",
    director: ["Giuseppe Tornatore"],
    stars: [
      "Philippe Noiret",
      "Enzo Cannavale",
      "Antonella Attili",
      "Isa Danieli",
    ],
    description: [
      "A",
      "filmmaker",
      "recalls",
      "his",
      "childhood",
      "when",
      "falling",
      "in",
      "love",
      "with",
      "the",
      "pictures",
      "at",
      "the",
      "cinema",
      "of",
      "his",
      "home",
      "village",
      "and",
      "forms",
      "a",
      "deep",
      "friendship",
      "with",
      "the",
      "cinema's",
      "projectionist.",
    ],
  },
  {
    id: "93",
    name: "The Best of Youth",
    year: "2003",
    runTime: "366",
    rating: "8.5",
    votes: "22797",
    metaScore: "89",
    gross: "270000",
    genre: ["Drama", "Romance"],
    certification: "R",
    director: ["Marco Tullio Giordana"],
    stars: [
      "Luigi Lo Cascio",
      "Alessio Boni",
      "Jasmine Trinca",
      "Adriana Asti",
    ],
    description: [
      "An",
      "Italian",
      "epic",
      "that",
      "follows",
      "the",
      "lives",
      "of",
      "two",
      "brothers",
      "from",
      "the",
      "1960s",
      "to",
      "the",
      "2000s.",
    ],
  },
  {
    id: "55",
    name: "Spirited Away",
    year: "2001",
    runTime: "125",
    rating: "8.6",
    votes: "811801",
    metaScore: "96",
    gross: "10060000",
    genre: ["Animation", "Adventure", "Family"],
    certification: "PG",
    director: ["Hayao Miyazaki"],
    stars: ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino", "Rumi Hiiragi"],
    description: [
      "During",
      "her",
      "family's",
      "move",
      "to",
      "the",
      "suburbs,",
      "a",
      "sullen",
      "10-year-old",
      "girl",
      "wanders",
      "into",
      "a",
      "world",
      "ruled",
      "by",
      "gods,",
      "witches",
      "and",
      "spirits,",
      "a",
      "world",
      "where",
      "humans",
      "are",
      "changed",
      "into",
      "beasts.",
    ],
  },
  {
    id: "191",
    name: "Like Stars on Earth",
    year: "2007",
    runTime: "165",
    rating: "8.3",
    votes: "201860",
    metaScore: "",
    gross: "1220000",
    genre: ["Drama", "Family"],
    certification: "PG",
    director: ["Aamir Khan", "Amole Gupte"],
    stars: ["Darsheel Safary", "Aamir Khan", "Tanay Chheda", "Sachet Engineer"],
    description: [
      "An",
      "eight-year-old",
      "boy",
      "is",
      "thought",
      "to",
      "be",
      "a",
      "lazy",
      "trouble-maker,",
      "until",
      "the",
      "new",
      "art",
      "teacher",
      "has",
      "the",
      "patience",
      "and",
      "compassion",
      "to",
      "discover",
      "the",
      "real",
      "problem",
      "behind",
      "his",
      "struggles",
      "in",
      "school.",
    ],
  },
  {
    id: "235",
    name: "Howl's Moving Castle",
    year: "2004",
    runTime: "119",
    rating: "8.2",
    votes: "425490",
    metaScore: "82",
    gross: "4710000",
    genre: ["Animation", "Adventure", "Family"],
    certification: "PG",
    director: ["Hayao Miyazaki"],
    stars: [
      "Chieko BaishÃ`",
      "Takuya Kimura",
      "Tatsuya GashÃ»in",
      "Akihiro Miwa",
    ],
    description: [
      "When",
      "an",
      "unconfident",
      "young",
      "woman",
      "is",
      "cursed",
      "with",
      "an",
      "old",
      "body",
      "by",
      "a",
      "spiteful",
      "witch,",
      "her",
      "only",
      "chance",
      "of",
      "breaking",
      "the",
      "spell",
      "lies",
      "with",
      "a",
      "self-indulgent",
      "yet",
      "insecure",
      "young",
      "wizard",
      "and",
      "his",
      "companions",
      "in",
      "his",
      "legged,",
      "walking",
      "castle.",
    ],
  },
  {
    id: "286",
    name: "The Kid",
    year: "1921",
    runTime: "68",
    rating: "8.2",
    votes: "131649",
    metaScore: "",
    gross: "5450000",
    genre: ["Comedy", "Drama", "Family"],
    certification: "Passed",
    director: ["Charles Chaplin"],
    stars: [
      "Charles Chaplin",
      "Edna Purviance",
      "Jackie Coogan",
      "Carl Miller",
    ],
    description: [
      "The",
      "Tramp",
      "cares",
      "for",
      "an",
      "abandoned",
      "child,",
      "but",
      "events",
      "put",
      "their",
      "relationship",
      "in",
      "jeopardy.",
    ],
  },
  {
    id: "294",
    name: "My Father and My Son",
    year: "2005",
    runTime: "112",
    rating: "8.2",
    votes: "89846",
    metaScore: "",
    gross: "",
    genre: ["Drama", "Family"],
    certification: "Not Rated",
    director: ["Ã‡agan Irmak"],
    stars: ["Ã‡etin Tekindor", "Fikret Kuskan", "HÃ¼meyra", "Ege Tanman"],
    description: [
      "The",
      "family",
      "of",
      "a",
      "left-wing",
      "journalist",
      "is",
      "torn",
      "apart",
      "after",
      "the",
      "military",
      "coup",
      "of",
      "Turkey",
      "in",
      "1980.",
    ],
  },
  {
    id: "327",
    name: "Harry Potter and the Deathly Hallows: Part 2",
    year: "2011",
    runTime: "130",
    rating: "8.1",
    votes: "918976",
    metaScore: "85",
    gross: "381010000",
    genre: ["Adventure", "Family", "Fantasy"],
    certification: "PG-13",
    director: ["David Yates"],
    stars: [
      "Daniel Radcliffe",
      "Emma Watson",
      "Rupert Grint",
      "Michael Gambon",
    ],
    description: [
      "Harry,",
      "Ron,",
      "and",
      "Hermione",
      "search",
      "for",
      "Voldemort's",
      "remaining",
      "Horcruxes",
      "in",
      "their",
      "effort",
      "to",
      "destroy",
      "the",
      "Dark",
      "Lord",
      "as",
      "the",
      "final",
      "battle",
      "rages",
      "on",
      "at",
      "Hogwarts.",
    ],
  },
  {
    id: "71",
    name: "Alien",
    year: "1979",
    runTime: "117",
    rating: "8.5",
    votes: "920996",
    metaScore: "89",
    gross: "78900000",
    genre: ["Horror", "Sci-Fi"],
    certification: "R",
    director: ["Ridley Scott"],
    stars: [
      "Sigourney Weaver",
      "Tom Skerritt",
      "John Hurt",
      "Veronica Cartwright",
    ],
    description: [
      "The",
      "crew",
      "of",
      "a",
      "commercial",
      "spacecraft",
      "encounters",
      "a",
      "deadly",
      "lifeform",
      "after",
      "investigating",
      "an",
      "unknown",
      "transmission.",
    ],
  },
  {
    id: "238",
    name: "The Thing",
    year: "1982",
    runTime: "109",
    rating: "8.2",
    votes: "448363",
    metaScore: "57",
    gross: "13780000",
    genre: ["Horror", "Mystery", "Sci-Fi"],
    certification: "16+",
    director: ["John Carpenter"],
    stars: ["Kurt Russell", "Wilford Brimley", "Keith David", "Richard Masur"],
    description: [
      "A",
      "research",
      "team",
      "in",
      "Antarctica",
      "is",
      "hunted",
      "by",
      "a",
      "shape-shifting",
      "alien",
      "that",
      "assumes",
      "the",
      "appearance",
      "of",
      "its",
      "victims.",
    ],
  },
  {
    id: "635",
    name: "The Blue Elephant",
    year: "2014",
    runTime: "170",
    rating: "8",
    votes: "29477",
    metaScore: "",
    gross: "",
    genre: ["Drama", "Horror", "Mystery"],
    certification: "Not Rated",
    director: ["Marwan Hamed"],
    stars: [
      "Karim Abdel Aziz",
      "Khaled El-Sawi",
      "Nilli Karim",
      "Mohamed Mamdouh",
    ],
    description: [
      "While",
      "trying",
      "to",
      "help",
      "an",
      "inmate",
      "at",
      "the",
      "mental",
      "hospital,",
      "a",
      "psychotherapist",
      "unravels",
      "mysteries",
      "he",
      "never",
      "thought",
      "existed.",
    ],
  },
  {
    id: "699",
    name: "Shaun of the Dead",
    year: "2004",
    runTime: "99",
    rating: "7.9",
    votes: "579854",
    metaScore: "76",
    gross: "13540000",
    genre: ["Comedy", "Horror"],
    certification: "R",
    director: ["Edgar Wright"],
    stars: ["Simon Pegg", "Nick Frost", "Kate Ashfield", "Lucy Davis"],
    description: [
      "The",
      "uneventful,",
      "aimless",
      "lives",
      "of",
      "a",
      "London",
      "electronics",
      "salesman",
      "and",
      "his",
      "layabout",
      "roommate",
      "are",
      "disrupted",
      "by",
      "the",
      "zombie",
      "apocalypse.",
    ],
  },
  {
    id: "868",
    name: "Get Out",
    year: "2017",
    runTime: "104",
    rating: "7.8",
    votes: "658776",
    metaScore: "85",
    gross: "176040000",
    genre: ["Horror", "Mystery", "Thriller"],
    certification: "R",
    director: ["Jordan Peele"],
    stars: [
      "Daniel Kaluuya",
      "Allison Williams",
      "Bradley Whitford",
      "Catherine Keener",
    ],
    description: [
      "A",
      "young",
      "African-American",
      "visits",
      "his",
      "White",
      "girlfriend's",
      "parents",
      "for",
      "the",
      "weekend,",
      "where",
      "his",
      "simmering",
      "uneasiness",
      "about",
      "their",
      "reception",
      "of",
      "him",
      "eventually",
      "reaches",
      "a",
      "boiling",
      "point.",
    ],
  },
  {
    id: "931",
    name: "Let the Right One In",
    year: "2008",
    runTime: "114",
    rating: "7.8",
    votes: "223207",
    metaScore: "82",
    gross: "2120000",
    genre: ["Drama", "Fantasy", "Horror"],
    certification: "R",
    director: ["Tomas Alfredson"],
    stars: ["KÃ¥re Hedebrant", "Lina Leandersson", "Per Ragnar", "Henrik Dahl"],
    description: [
      "Oskar,",
      "an",
      "overlooked",
      "and",
      "bullied",
      "boy,",
      "finds",
      "love",
      "and",
      "revenge",
      "through",
      "Eli,",
      "a",
      "beautiful",
      "but",
      "peculiar",
      "girl.",
    ],
  },
];
